### ISSUE TITLE
Redesign Footer

### ISSUE THREAD

**Issue by arpita221b** [Xtremilicious/projectlearn-project-based-learning#38]
For now, it looks like this:

![Screenshot (1170)](https://user-images.githubusercontent.com/56889637/145000285-5078e5da-14d3-4448-8752-6c93ed0bb452.png)

I would like to redesign it to this:

![Screenshot (1169)](https://user-images.githubusercontent.com/56889637/145000457-8811e77d-f639-4e55-a64e-c4489dfc8245.png)

Please assign this issue to me if it looks fine.

**Comment by Xtremilicious** [comment]
Yep, looks great! However, the icons don't look that good - maybe a text-only link column(about, contribution, GitHub repo) would be nice. 

Here are some footer design ideas that you might wanna have a look at: https://webflow.com/blog/website-footer-design-examples

**Comment by arpita221b** [comment]
Okay sure I'll fix that!
