### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by psankhe28** [Xtremilicious/projectlearn-project-based-learning#42]
I would like to redesign navbar.Please assign this issue to me

**Comment by Xtremilicious** [comment]
Hey, @psankhe28 thanks for your interest in contributing to ProjectLearn.

As a starting step, please share mockup designs of your ideas regarding the Navbar. We can discuss revisions if needed, and then the development of the same can be started.

**Comment by psankhe28** [comment]
So,I would Like to make a navbar in the left side.Initially only the icons will be displayed and on hovering the circles,we will get to see Home,Blog as a whole word like in the below picture:

<img width="91" alt="image" src="https://user-images.githubusercontent.com/84843461/147467042-75c88d2c-1e27-4ef7-80e9-09345d758563.png">

The design will be as follows...also i would like to add  animation to the image in that pink box and style the get started button.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/84843461/147466887-b122c48a-8d12-4e8a-864d-9ef3a4458766.png">

Please suggest any revision if you want.Thanks!

**Comment by Xtremilicious** [comment]
Hey, @psankhe28 looks a bit cramped - also have you considered the mobile view?

A navbar redesign like the one below would be ideal. 
The current Home, blog and Github star count can be centred(you need to keep the GitHub star live coiunt feature as it is) while leaving space for a potential Login button at the right.

![2021-12-27 19_39_22-Nav Polish by Alejandro Vizio for Pachama on Dribbble](https://user-images.githubusercontent.com/47635607/147479432-15312b76-bbc6-4069-a0f2-3f7beb03ccd3.png)

**Comment by psankhe28** [comment]
The design you have suggested looks great!

If we consider my design,for the mobile view,I think we can have a hamburger icon and a side bar can appear..like the one in below picture

<img width="181" alt="image" src="https://user-images.githubusercontent.com/84843461/147493596-051f8255-9102-48c1-833e-883fbb2e6688.png">

Also,the navbar can be done for mobile view as it is mentioned above by you.Do consider my design too and please let me know.Thanks!

**Comment by Xtremilicious** [comment]
@psankhe28 mobile view looks good, however - the desktop view in your design looks a bit cramped, it's better to keep the nav elements as a horizontal bar rather than taking up vertical screen space.

The GitHub star count functionality and styling should be intact, as well.

**Comment by psankhe28** [comment]
Ok fine.I would start working on the design suggested by you

**Comment by heet-kumar** [comment]
@psankhe28 any updates till now how much work is done.

**Comment by psankhe28** [comment]
> @psankhe28 any updates till now how much work is done.

I have almost completed it.By tomorrow,i will make a pull request.

**Comment by psankhe28** [comment]
Please find the attached screenshot of navbar and suggest any changes if needed.Thanks!

For desktop:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/84843461/148698529-e25197d8-59d4-407d-ad86-e57d98d16a7b.png">

For mobile:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/84843461/148698549-b7e9363b-49d6-4839-baa0-a05963f17d5b.png">

**Comment by Xtremilicious** [comment]
Hey @psankhe28. I don't feel this is similar to the mockup that was decided upon, [as above](https://github.com/Xtremilicious/projectlearn-project-based-learning/issues/42#issuecomment-1001587082)?

Also a few questions:
1. How is the UX subjectively better than the original UI that we have in production?
For comparison:
![Untitled-1](https://user-images.githubusercontent.com/47635607/148767497-41a82506-bf24-4a91-b946-d6fd4bc7b4c3.png)

The new Navbar looks uneven (dark on light) - not in accordance with the rest of the website's feel.

2. The GitHub star UI looks much better on the original.
![image](https://user-images.githubusercontent.com/47635607/148767699-d0337b1f-5a1a-425f-be78-fadb9ae36368.png)


I hope that you learned something and appreciate the work that you did, but unless your contributions enhance the user experience, it cannot be pushed to production.

What I can suggest right now - is to follow this design solution and try to incorporate it:
![147479432-15312b76-bbc6-4069-a0f2-3f7beb03ccd3](https://user-images.githubusercontent.com/47635607/148767810-25f7df69-aca6-4801-845b-a5c09d77d22d.png)

**Comment by psankhe28** [comment]
> Hey @psankhe28. I don't feel this is similar to the mockup that was decided upon, [as above](https://github.com/Xtremilicious/projectlearn-project-based-learning/issues/42#issuecomment-1001587082)?
> 
> Also a few questions:
> 
> 1. How is the UX subjectively better than the original UI that we have in production?
>    For comparison:
>    ![Untitled-1](https://user-images.githubusercontent.com/47635607/148767497-41a82506-bf24-4a91-b946-d6fd4bc7b4c3.png)
> 
> The new Navbar looks uneven (dark on light) - not in accordance with the rest of the website's feel.
> 
> 2. The GitHub star UI looks much better on the original.
>    ![image](https://user-images.githubusercontent.com/47635607/148767699-d0337b1f-5a1a-425f-be78-fadb9ae36368.png)
> 
> I hope that you learned something and appreciate the work that you did, but unless your contributions enhance the user experience, it cannot be pushed to production.
> 
> What I can suggest right now - is to follow this design solution and try to incorporate it: ![147479432-15312b76-bbc6-4069-a0f2-3f7beb03ccd3](https://user-images.githubusercontent.com/47635607/148767810-25f7df69-aca6-4801-845b-a5c09d77d22d.png)

Sry for the inconvenience caused. I will redesign it.

**Comment by nawed2611** [comment]
Hi! If this issue is open, I would like to work on it!
