### ISSUE TITLE
Wrong link on "Learn CSS Basics by Building a Card Component" page

### ISSUE THREAD

**Issue by PauloBacelar** [Xtremilicious/projectlearn-project-based-learning#43]
The button link on [this page](https://projectlearn.io/learn/web-development/project/learn-css-basics-by-building-a-card-component-196?from=github) is wrong. It refs to "ehttps" instead of just "https" and user can't access the page

**Comment by Xtremilicious** [comment]
Thanks @PauloBacelar. Fixed!
