### ISSUE TITLE
Building a Card Component

### ISSUE THREAD

**Issue by Arceus-sj** [Xtremilicious/projectlearn-project-based-learning#44]
I would like to design and code Info card component using HTML, CSS, Bootstrap 5.
Please assign this task to me.

**Comment by Xtremilicious** [comment]
Hey @Arceus-sj, thanks for your interest in contributing to ProjectLearn.



Problem Statement: Several suggestions point towards a redesign of our project card component.
This is our current design: Preview link: https://projectlearn.io/learn/web-development

![image](https://user-images.githubusercontent.com/47635607/148413690-59f272c1-2eda-40e5-b010-7bcd3b6e54dc.png)

As a starting step, please share mockup designs of your idea regarding the card component (as shown above) -  How to make it more intuitive, and more appealing?

**Comment by Arceus-sj** [comment]
Sorry for the delay sir but I used Figma for the first time and yesterday I learned how to use the tools given in figma.
So, today I create a card component design. Look at the design and give your views on it.
![Card Component](https://user-images.githubusercontent.com/71997730/148634214-a7956852-e23c-45cb-b9d5-d0e747447c54.jpg)

**Comment by Arceus-sj** [comment]
Should I start with coding part or Is there any thing you want to change?

**Comment by Xtremilicious** [comment]
Looks pretty good to me. 
The green arrow button can be omitted- instead, the arrow functionality can be given to the whole card itself - that is, on clicking the card, it takes you to the project details page.

I'm assuming you have already run this project locally.
- But before you start coding, have a look and play with this file (includes CSS as well as HTML/JS):
The card component lies in ` projectlearn-project-based-learning/src/components/Dashboard/Content/Project.js `
- Make some code/CSS changes to see the changes in action on your locally deployed project.

Let me know if you have any questions.

**Comment by Arceus-sj** [comment]
1. I will remove the arrow icon.
2. Can you explain little bit about which repo i have to fork and clone.

**Comment by Arceus-sj** [comment]
And talking about the top technologies, If I will get all the technologies icons then I will change them but it take some time otherwise I will change the style of all the technologies and give them a unique colour with same font.
is that okay?

**Comment by Xtremilicious** [comment]
> 1. I will remove the arrow icon.
> 2. Can you explain little bit about which repo i have to fork and clone. Then I am able to run the project locally.

https://github.com/Xtremilicious/projectlearn-project-based-learning

**Comment by Xtremilicious** [comment]
> And talking about the top technologies, If I will get all the technologies icons then I will change them but it take some time otherwise I will change the style of all the technologies and give them a unique colour with same font. is that okay?

I don't think that's practical. Let's keep it as text for now. Do share a revised mockup with the technologies as text - to make them more appealing.

**Comment by Arceus-sj** [comment]
> > And talking about the top technologies, If I will get all the technologies icons then I will change them but it take some time otherwise I will change the style of all the technologies and give them a unique colour with same font. is that okay?
> 
> I don't think that's practical. Let's keep it as text for now. Do share a revised mockup with the technologies as text - to make them more appealing.

**Comment by Arceus-sj** [comment]
Okay i will do that 

> > And talking about the top technologies, If I will get all the technologies icons then I will change them but it take some time otherwise I will change the style of all the technologies and give them a unique colour with same font. is that okay?
> 
> I don't think that's practical. Let's keep it as text for now. Do share a revised mockup with the technologies as text - lets see how we can make the styling more appealing

Okay I will do that.

**Comment by Arceus-sj** [comment]
Check this out I thick it looks ok now.
what do you think?
![card](https://user-images.githubusercontent.com/71997730/148639062-9d88ee6a-3c0a-4cd1-a1c7-e62d5965e32f.jpg)

**Comment by Xtremilicious** [comment]
Yep, you can start dev in the cloned repo. Would love to keep a track of your daily/periodic progress as well. You can share screenshots in this thread, or ask any queries that you may have.

Just a reminder. Make your changes in this file only: 
The card component lies in` projectlearn-project-based-learning/src/components/Dashboard/Content/Project.js`

**Comment by Arceus-sj** [comment]
@Xtremilicious I am facing problem while run this project locally. Do I have to delete the yarn.lock file?

**Comment by Xtremilicious** [comment]
> @Xtremilicious I am facing problem while run this project locally. Do I have to delete the yarn.lock file?

Nope, make sure you are in the correct folder:
Run:
npm install
npm run dev

Share screenshots of your issue - that would be more helpful.

**Comment by nawed2611** [comment]
Hi! I would like to work/collab on this issue, if its yet to be resolved yet!

**Comment by Riya123-code** [comment]
can i work on this issue?
