### ISSUE TITLE
Incorrect Link for project "Chat App with Sentiment Analysis"

### ISSUE THREAD

**Issue by latrujil913** [Xtremilicious/projectlearn-project-based-learning#62]
Hi, it seems like the link for "Chat App with Sentiment Analysis" leads to another project titled "Build an Appointment Scheduler Using React, Twilio, and Cosmic JS." Is this as intended? 

P.S. thanks for the fantastic resource!

**Comment by Xtremilicious** [comment]
Thanks @latrujil913! fixed the link :)
