### ISSUE TITLE
Suggestion to Make Website Fully Responsive

### ISSUE THREAD

**Issue by sahilatahar** [Xtremilicious/projectlearn-project-based-learning#90]
The website's grid card layout is not fully responsive across different screen sizes and devices. This issue impacts the user experience as the cards may not display correctly on smaller screens or in other orientations.

**Suggestion**:
- Improve the responsiveness of the grid card layout to ensure it adapts well to various screen sizes and orientations.
- Assign this task to me, and I will work on implementing the necessary changes to make the website fully responsive.

**Comment by Xtremilicious** [comment]
Hi @sahilatahar, I am currently looking into migrating into a design framework to keep everything consistent. This will help in making it more responsive.
